version: '3.3'

services:
  mysql:
    image: mysql:5
    container_name: dbmysql
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80